apiVersion: apps/v1
kind: Deployment
metadata:
  name: consumer-health-check-service
  namespace: kafka-healthcheck
spec:
  replicas: 1
  selector:
    matchLabels:
      app: consumer-health-check-service
  template:
    metadata:
      labels:
        app: consumer-health-check-service
    spec:
      containers:
      - name: consumer-health-check-service
        image: consumer_health_check_service:latest
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
          requests:
            memory: "256Mi"
            cpu: "250m"
        ports:
        - containerPort: 5001
        imagePullPolicy: Never
---
apiVersion: v1
kind: Service
metadata:
  name: consumer-health-check-service
  namespace: kafka-healthcheck
spec:
  selector:
    app: consumer-health-check-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5001