apiVersion: apps/v1
kind: Deployment
metadata:
  name: consumer-health-check-service
  labels:
    app: consumer-health-check-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: consumer-health-check-service
  template:
    metadata:
      labels:
        app: consumer-health-check-service
    spec:
      containers:
        - name: consumer-health-check-service
          image: <your-docker-registry>/consumer-health-check-service:latest
          ports:
            - containerPort: 8080
          env:
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: kafka:9092
          resources:
            limits:
              cpu: 500m
              memory: 512Mi
            requests:
              cpu: 100m
              memory: 256Mi